### DISCUSSION TITLE
checkbox icon is not centered when checked

### DISCUSSION THREAD

**Discussion by Liripo** [unovue/shadcn-vue#1211] [Q&A] [answered]
I used the checkbox directly, but the icon was not centered. 
![image](https://github.com/user-attachments/assets/0c04f60c-85f8-4655-8ebc-39b9a3ccb9ff)

**Comment by Liripo** [comment, marked as answer]
```css
.lucide {
  width: 24px;
  height: 24px;
  stroke-width: 2px;
}
```
It turned out that I modified the global icon.
